#!/bin/bash

failed () {
	echo -e '\n  \e[1;31mfailed '$@'\e[0m\n' >&2
	exit 1
}

type npm > /dev/null || failed to locate the npm tool
type npx > /dev/null || failed to locate the npx tool

test -e node_modules || {
	npm install -D || failed to install dependencies
}
test -e dist && {
	rm -rf dist && mkdir dist
}

npx sass styles.scss | node daniela.mjs - || \
failed to transpile and minify styles.scss

npx tsc --build && {
	node daniela.mjs || failed to minify index.js
} || failed to transpile index.ts
