#!/bin/bash

failed () {
	echo -e '\n  \e[1;31mfailed '$@'\e[0m\n' >&2
	exit 1
}

type minify > /dev/null || failed to locate the minify tool

npx -q sass styles.scss | \
minify --type css -o dist/daniela.min.css || \
failed to transpile styles.scss

npx -q tsc --build && {
	node daniela.mjs index.js | \
	minify --type js -o dist/daniela.min.js || \
	failed to process index.js
} || failed to transpile index.ts
